services:
  db:
    image: postgres:16
    container_name: freight_sql_db
    environment:
      POSTGRES_USER: freight
      POSTGRES_PASSWORD: freight
      POSTGRES_DB: freightdb
    ports:
      - "5432:5432"
    volumes:
      - freight_pgdata:/var/lib/postgresql/data

volumes:
  freight_pgdata:
